# Purpose of this Dockerfile is to create a VIC image that runs nested Docker that can be accessed securely via docker exec
# You can use this image to build Docker images, general development, run tests etc.

# See README for more details

FROM vmware/photon

RUN tdnf install -y procps-ng iptables net-tools docker 1.12.6-1.ph1

CMD /usr/bin/dockerd -s overlay2 $DOCKER_OPTS
